name: Check okd stable releases

on:
  workflow_dispatch:
jobs:
    check:
        name: Get OKD releases and compare to branches
        runs-on: ubuntu-24.04
        steps:
        - name: Set up Podman, OpenShift CLI, and Skopeo
          run: |
            echo "Installing Podman"
            sudo apt-get update
            sudo apt-get install -y podman

            echo "Installing OpenShift CLI"
            curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz"
            tar -xvf openshift-client-linux.tar.gz
            sudo mv oc /usr/local/bin/
            sudo mv kubectl /usr/local/bin/
            rm -f openshift-client-linux.tar.gz

            echo "Installing Skopeo"
            sudo apt-get install -y skopeo
        - name: find OKD tags
          run: |
             skopeo inspect docker://quay.io/okd/scos-release:4.17.0-okd-scos.2 | jq '.RepoTags[] |select (test("4.[1-2][6-9].0-okd-scos.[0-9]"))'
        - name: get urls
          run: |
            { echo 'OKD_COMMITS=<<EOF'
              oc adm release info --commit-urls -f json quay.io/okd/scos-release:4.17.0-okd-scos.2
              echo EOF
            } >> '$GITHUB_ENV'
