name: Build DDK containers

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  QUAY:
  
jobs:
  build:
    name: build containers
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.8.0
        with:
          cosign-release: 'v2.2.4'    

      - name: Check install!
        run: cosign version
# Build Base Image
      - name: Build base Image
        id: build_base_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: base
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          oci: true
          layers: true
          containerfiles: ./openshift-images/base/Dockerfile.rhel9
          context: ./openshift-images/base/
          
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push_base_image
        with:
          image: ${{ steps.build_base_image.outputs.image }}
          tags: ${{ steps.build_base_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
      - name: Sign the images with GitHub OIDC Token
        env:
          PATHS: ${{ steps.build_base_image.outputs.registry-paths }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${{ steps.build_base_image.outputs.registry-path }}
# Build Router Images
      - name: Build router base Image
        id: build_base_router_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: router-base
          tags: latest ${{ github.sha }}
          archs: amd64, arm64
          oci: true
          containerfiles: ./openshift-router/images/router/base/Dockerfile.ocp
          context: ./openshift-router/

      - name: Build Router Haproxy Image
        id: build_router_haproxy_image
        uses: redhat-actions/buildah-build@v2
        with:
            image: ${{ env.IMAGE_NAME }}
            tags: latest ${{ github.sha }}
            archs: amd64, arm64
            oci: true
            containerfiles: ./openshift-router/images/router/haproxy/Dockerfile.ocp
            context: ./openshift-router/
