name: Build group 2 of DDK containers test

on:
  workflow_call:
env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  QUAY:
  
jobs:
  build:
    name: build containers
    runs-on: ubuntu-24.04
    steps:   
      - name: Set up Podman, OpenShift CLI, and Skopeo
        run: |
          echo "Installing"
          sudo apt-get update
          sudo apt-get install -y podman buildah skopeo
          echo "Installing OpenShift CLI"
          curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux-arm64.tar.gz"
          tar -xvf openshift-client-linux-arm64.tar.gz
          sudo mv oc /usr/local/bin/
          sudo mv kubectl /usr/local/bin/
          rm -f openshift-client-linux.tar.gz
      - name: Remove unwanted stuff to free up disk image
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /opt/hostedtoolcache/CodeQL

          sudo docker image prune --all --force

          sudo swapoff -a
          sudo rm -f /mnt/swapfile

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        

# Build Kube Proxy Image
      - name: Build router base Image
        id: build_proxy_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: kube-proxy
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          oci: true
          layers: true
          containerfiles: ./openshift-sdn/images/kube-proxy/Dockerfile.rhel
          context: ./openshift-sdn/
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push_proxy_image
        with:
          image: ${{ steps.build_proxy_image.outputs.image }}
          tags: ${{ steps.build_proxy_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}

# Build CSI Images
      - name: Build CSI Controller Image
        id: build_csi_controller_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: csi-snapshot-controller
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          oci: true
          layers: true
          containerfiles: ./openshift-csi-external-snapshotter/Dockerfile.snapshot-controller.openshift.rhel7
          context: ./openshift-csi-external-snapshotter/
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push_csi_controller_image
        with:
          image: ${{ steps.build_csi_controller_image.outputs.image }}
          tags: ${{ steps.build_csi_controller_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}

# Build Kube rbac Proxy Image
      - name: Build Kube rbac Proxy Image
        id: build_rbac_proxy_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: kube-rbac-proxy
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          oci: true
          layers: true
          containerfiles: ./openshift-coredns/Dockerfile.ocp
          context: ./openshift-coredns/
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push_rbac_proxy_image
        with:
          image: ${{ steps.build_rbac_proxy_image.outputs.image }}
          tags: ${{ steps.build_rbac_proxy_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}

          
# Build Openshift Containernetworking Plugins Image
      - name: Build Openshift Containernetworking Plugins Image
        id: build_openshift_containernetworking_plugins_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: kube-rbac-proxy
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          oci: true
          layers: true
          containerfiles: ./openshift-containernetworking-plugins/Dockerfile.microshift
          context: ./openshift-containernetworking-plugins/
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push_openshift_containernetworking_plugins_image
        with:
          image: ${{ steps.build_openshift_containernetworking_plugins_image.outputs.image }}
          tags: ${{ steps.build_openshift_containernetworking_plugins_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}

# Build Pod Image
      - name: Build pod Image
        id: build_pod_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: pod
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          oci: true
          layers: true
          containerfiles: ./kubernetes/build/pause/Dockerfile.Rhel
          context: ./kubernetes/build/pause/
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push_pod_image
        with:
          image: ${{ steps.build_pod_image.outputs.image }}
          tags: ${{ steps.build_pod_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}

# Build Service CA Operator Image
      - name: Build Service CA Operator Image
        id: build_service_ca_operator_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: service-ca-operator
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          oci: true
          layers: true
          containerfiles: ./openshift-oc/images/cli/Dockerfile.rhel
          context: ./openshift-oc/
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push_service_ca_operator_image
        with:
          image: ${{ steps.build_service_ca_operator_image.outputs.image }}
          tags: ${{ steps.build_service_ca_operator_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
